# Generated by Django 3.2.2 on 2021-05-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rec_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_elemento', models.CharField(max_length=250)),
                ('mat_descripcion', models.CharField(max_length=2000)),
                ('mat_video', models.CharField(max_length=500)),
                ('mat_imagen', models.CharField(max_length=250)),
                ('mat_url', models.CharField(max_length=250)),
            ],
        ),
    ]
